# Generated by Django 5.0.1 on 2024-02-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='my_order',
            field=models.PositiveIntegerField(blank=True, db_index=True, default=1, null=True),
        ),
    ]
