# Generated by Django 5.0.2 on 2024-03-29 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_gallery_options_alter_image_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='images',
            field=models.ManyToManyField(related_name='galleries', through='portfolio.ImageInGallery', to='portfolio.image'),
        ),
    ]
