# Generated by Django 5.0.2 on 2024-04-03 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_gallery_images'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name_plural': 'galleries'},
        ),
    ]
