# Generated by Django 5.0.4 on 2024-04-07 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_gallery_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='main_image',
            field=models.FileField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
