# Generated by Django 5.0.4 on 2024-04-07 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_gallery_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
