# Generated by Django 5.0.4 on 2024-05-04 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_gallery_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name_plural': 'Galleries'},
        ),
    ]
