# Generated by Django 5.0.4 on 2024-05-04 15:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_alter_gallery_options_gallery_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='main_image',
            field=models.FileField(null=True, upload_to='images/'),
        ),
    ]
