# Generated by Django 5.0.4 on 2024-05-04 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_alter_gallery_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='main_image',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='type',
            field=models.CharField(choices=[('main', 'Main Page'), ('serie', 'Serie')], default='serie', max_length=10),
        ),
    ]
