# Generated by Django 5.0.4 on 2024-05-04 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_alter_gallery_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='main_image',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
