# Generated by Django 5.0.4 on 2024-05-04 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_alter_gallery_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='main_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.image'),
        ),
    ]
