# Generated by Django 5.0.4 on 2024-05-05 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0019_alter_gallery_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageingallery',
            name='gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_in_gallery', to='portfolio.gallery'),
        ),
    ]
