# Generated by Django 5.0.4 on 2024-05-05 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0020_alter_imageingallery_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageingallery',
            name='gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.gallery'),
        ),
    ]
