# Generated by Django 5.0.4 on 2024-05-05 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0021_alter_imageingallery_gallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='main_image',
        ),
    ]
