# Generated by Django 5.0.4 on 2024-05-14 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0023_image_height_image_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageingallery',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
