# Generated by Django 5.0.4 on 2024-05-14 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0024_imageingallery_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageingallery',
            name='slug',
            field=models.SlugField(default='', null=True),
        ),
    ]
