# Generated by Django 5.0.4 on 2024-05-14 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0025_alter_imageingallery_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageingallery',
            name='slug',
        ),
    ]
