# Generated by Django 5.0.4 on 2024-06-15 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0026_remove_imageingallery_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='title_image',
            field=models.FileField(default=123, upload_to='images/'),
            preserve_default=False,
        ),
    ]
