# Generated by Django 5.0.4 on 2024-08-10 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0028_alter_gallery_title_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
    ]
